### ISSUE TITLE
bump version number?

### ISSUE THREAD

**Issue by csylvain** [adafruit/Adafruit_SSD1325_Library#4]
have Arduino IDE and this library version "1.0.0" installed via Library Manager.

up-to-date version here has definition for adagfx_swap() but the version obtained with Library Manager has no definition for AdaGFX_swap()

workaround: download zip from here to update library

possible solution: bump version to 1.0.1 to prompt fresh library download and reinstallation

**Comment by caternuson** [comment]
Closing. Version has been bumped.
