### ISSUE TITLE
Error compiling library example when using RP2040

### ISSUE THREAD

**Issue by ashirvadz** [adafruit/Adafruit_SSD1325_Library#6]
- Arduino board:  Adafruit Feather RP2040 RFM69

- Arduino IDE version: 2.1.0

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):  Error when compiling the library's example file (ssd1325test.ino).

```/Users/ashirvad/Library/Arduino15/packages/rp2040/hardware/rp2040/3.3.0/cores/rp2040/api/../../../ArduinoCore-API/api/deprecated-avr-comp/avr/pgmspace.h:116:29: note: in expansion of macro 'pgm_read_byte'
  116 | static inline unsigned char pgm_read_byte(const void *addr) {
      |                             ^~~~~~~~~~~~~

exit status 1

Compilation error: exit status 1
```
There's no error when I use the same code/IDE with an Adafruit Feather M0 RFM69.  
I need this to work because I am working on a device that needs the RP2040 board and has a tight deadline.  
Can someone please advise me what to do?   
Thank you.

**Comment by ladyada** [comment]
should be fixed now
